// Auto-generated by NLS Refactor. Do not edit manually.
const { translate } = require('./nls_loader');

const nls_ts = {
  app: {
    description: "app.description"
  },
  configuration: {
    title: "configuration.title",
    generateTests: {
      defaultRootDir: "configuration.generateTests.defaultRootDir",
      defaultOutputDir: "configuration.generateTests.defaultOutputDir",
      overwrite: "configuration.generateTests.overwrite",
      skipIndexJs: "configuration.generateTests.skipIndexJs",
      iife: "configuration.generateTests.iife"
    }
  },
  extension: {
    firsttime: {
      run: {
        message: "extension.firsttime.run.message"
      },
      select: {
        source: {
          folder: {
            title: "extension.firsttime.select.source.folder.title"
          }
        },
        test: {
          folder: {
            title: "extension.firsttime.select.test.folder.title"
          }
        }
      }
    },
    completion: {
      message: "extension.completion.message"
    }
  }
};

module.exports = { nls_ts, translate };