// Auto-generated by NLS Refactor. Do not edit manually.
const { translate } = require('./nls_loader');

const nls_ts = {
  app: {
    description: "app.description"
  },
  configuration: {
    title: "configuration.title",
    generateTests: {
      defaultRootDir: "configuration.generateTests.defaultRootDir",
      defaultOutputDir: "configuration.generateTests.defaultOutputDir",
      overwrite: "configuration.generateTests.overwrite",
      skipIndexJs: "configuration.generateTests.skipIndexJs",
      iife: "configuration.generateTests.iife"
    }
  },
  extension: {
    firsttime: {
      run: {
        message: "extension.firsttime.run.message"
      },
      select: {
        source: {
          folder: {
            title: "extension.firsttime.select.source.folder.title"
          }
        },
        test: {
          folder: {
            title: "extension.firsttime.select.test.folder.title"
          }
        }
      }
    },
    completion: {
      message: "extension.completion.message"
    }
  },
  jsgeneratetests: {
    generateTests: {
      run: {
        title: "jsgeneratetests.generateTests.run.title"
      },
      settings: {
        title: "jsgeneratetests.generateTests.settings.title"
      }
    }
  },
  jsgenerateTests: {
    submenu: {
      title: "jsgenerateTests.submenu.title"
    }
  },
  error: {
    common: {
      template: "error.common.template"
    }
  },
  currentOverwrite: {
    text: "currentOverwrite.text"
  },
  currentNoSkipIndex: {
    text: "currentNoSkipIndex.text"
  },
  currentIife: {
    text: "currentIife.text"
  },
  generation: {
    extra: {
      options: {
        placeholder: "generation.extra.options.placeholder"
      }
    }
  },
  run: {
    generator: {
      title: "run.generator.title"
    }
  },
  select: {
    folder: {
      placeholder: "select.folder.placeholder"
    }
  }
};

module.exports = { nls_ts, translate };